---
title: "Design Principles for {epiparameterDashboard}"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design Principles for {epiparameterDashboard}}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette outlines the design decisions that have been taken during the development of `{epiparameterDashboard}`, and provides some of the reasoning, and possible pros and cons of each decision.

This document is primarily intended to be read by those interested in understanding the code within the package and for potential package contributors.

<!-- Text in angular brackets (<>) is to guide what to include for each section please delete the guidelines and replace for your package.

None of the sections are required, feel free to remove any sections not relevant to your package or add new sections if helpful. -->

## Scope

`{epiparameterDashboard}` aims to provide a user-friendly interface for exploring the parameters provided by the `{epiparameter}` and `{epireview}` packages.

## Use cases

- Modellers who would like to compare existing parameters in the database to choose the most appropriate for their model.
- Researchers who would like to compare new estimates to existing parameters.
- Individuals who would like to generate a report of the parameters in the database, including key summary statistics and plots for a report.
  
## Minimal interface

- Sufficient summary statistics: show multiple studies at the same time. 
- A comparison of available distributions for the same disease, allowing user interactivity by selecting citations to visualise.
- Ability to highlight/select individual lines on the plot and see its associated information.
- Context from which parameters were obtained (available in `{epireview}`): community-based, health care workers, etc.
- An option to download a report containing the code used to generate the dashboard visuals, and information on the disease, delay distribution, and other associated information (citation, etc).
- Provide an easy way to copy parameter estimates and citation.

### Out of scope

- Impact of different parameters on downstream estimates of $Rt$, $CFR$, etc.

## Design decisions

## Input/Output/Interoperability

- `{epiparameterDashboard}` will read in the data provided by `{epiparameter}` and `{epireview}` as `<data.frame>` and output the dashboard that provides options to visualise parameters from the two packages separately and compare values across the two packages.

## Dependencies

- The ability to download static output, for example, a report, will determine whether to use `{flexdashboard}` vs `shiny`.

- plotly (for interactivity with plots)
- Shiny (for dashboard)
- flexdashboard (for dashboard)
- epiparameter (for data and functions)
- epireview (for data and functions)
- DT (for tables)
